version: '3.7'
services:

  webapp:
    #image: gcr.io/core-iot-sensors/rpifocus-webapp:1.0.0
    image: lemariva/rpifocus-webapp:1.0.0
    restart: unless-stopped
    ports:
      - 4200:4200
    volumes:
      - db-gallery:/root/webapp/src/photos/gallery
      - db-raw:/root/webapp/src/photos/raw
    depends_on:
      - backend
    networks:
      - rpifocus

  backend:
    #image: gcr.io/core-iot-sensors/rpifocus-backend:1.0.0
    image: lemariva/rpifocus-backend:1.0.0
    restart: unless-stopped
    privileged: true
    environment:
      - LD_LIBRARY_PATH=/opt/vc/lib
      - HOST_M5STACK=192.168.178.71
      - HOST_OBJ_DETECTOR=obj-detector
      - PORT_OBJ_DETECTOR=8010
      - HOST_PHOTO_SERVICE=http://photo-service:8005
      - GALLERY_PATH=/mnt/gallery
    ports:
      - 5000:5000
    expose:
      - 5000
    volumes:
      - /opt/vc:/opt/vc
      - db-gallery:/mnt/gallery
      - db-raw:/mnt/raw
    devices:
      - /dev/vcsm:/dev/vcsm
      - /dev/vchiq:/dev/vchiq
      - /dev/video0:/dev/video0
    depends_on:
      - obj-detector
      - photo-service
    networks:
      - rpifocus

  obj-detector:
    #image: gcr.io/core-iot-sensors/rpifocus-objdetector:1.0.0
    image: lemariva/rpifocus-objdetector:1.0.0
    restart: unless-stopped
    privileged: true
    environment:
      - PORT_OBJ_DETECTOR=8010
      - MODEL_PATH=data/mobilenet_ssd_v2_coco_quant_postprocess_edgetpu.tflite
      - LABELS_PATH=data/coco_labels.txt
      - THRESHOLD=0.3
      - TOP_K=5
    expose:
      - 8010
    volumes:
      - /dev/bus/usb:/dev/bus/usb
    networks:
      - rpifocus

  photo-service:
    #image: gcr.io/core-iot-sensors/rpifocus-photoservice:1.0.0
    image: lemariva/rpifocus-photoservice:1.0.0
    restart: unless-stopped
    privileged: true
    environment:
      - LD_LIBRARY_PATH=/opt/vc/lib
      - PHOTO_TMP_PATH=/mnt/ramdisk
      - PHOTO_GALLERY_PATH=/mnt/gallery
      - PHOTO_RAW_PATH=/mnt/raw
      - HOST_REDIS=redis
      - PORT_RESTAPI=8005
    expose:
      - 8005
    volumes:
      - /opt/vc:/opt/vc
      - /mnt/ramdisk:/mnt/ramdisk
      - db-gallery:/mnt/gallery
      - db-raw:/mnt/raw
    devices:
      - /dev/vcsm:/dev/vcsm
      - /dev/vchiq:/dev/vchiq
      - /dev/video0:/dev/video0
    depends_on:
      - redis
    networks:
      - rpifocus

  redis:
    image: redis
    restart: unless-stopped
    container_name: redis
    expose:
      - 6379
    networks:
      - rpifocus

volumes:
  db-gallery:
  db-raw:

networks:
  rpifocus: