steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', 
          '-t', 'gcr.io/$PROJECT_ID/rpifocus-webapp:${_MAYOR_REVISION}.${_MINOR_REVISION}.${_BUILD_ID}', 
          '--build-arg',
          'BUILD_ID=${_BUILD_ID}',
          '--build-arg',
          'MAYOR_REVISION=${_MAYOR_REVISION}',
          '--build-arg',
          'MINOR_REVISION=${_MINOR_REVISION}',
          '.']
substitutions:  # default values
  _MAYOR_REVISION: "1"
  _MINOR_REVISION: "0"
  _BUILD_ID: "0"
timeout: 5400s
images:
- 'gcr.io/$PROJECT_ID/rpifocus-webapp'